### ISSUE TITLE
Access bookmarks via API

### ISSUE THREAD

**Issue by DahlitzFlorian** [Medium/medium-sdk-python#11]
Would be great if I could access my bookmarks via Python API. 

Or is there already a way to do this?

**Comment by kylewm** [comment]
The Medium API is write-only -- Unfortunately we don't have an API to pull stories or bookmarks.

**Comment by DahlitzFlorian** [comment]
Is there any interest in creating an API or enhancing the already existing one, so that it's possible to access bookmarks via API call?

**Comment by sanromd** [comment]
+1 It seems this is a feature that lots of us need. Is there a plan to add it to the api calls?
