### ISSUE TITLE
[feature-request] Implement publication API 

### ISSUE THREAD

**Issue by ArtOfCode-** [Medium/medium-sdk-python#7]
I'd like to see an API in here for interacting with publications (publishing to them and managing them). This seems like the next logical step towards the API being full-coverage.

Within this (though also for single users), I'd like to see an API for getting publication or user stats - it is, of course, possible to reverse-engineer Medium's internal API to get the stats, but using such a technique would be forbidden by the no-scrape requirement in the TOS.

**Comment by huckphin** [comment]
This report is unrelated to the Python SDK but related to the overall API. For API feature requests, those are handled in the [medium-api-docs repository](https://github.com/Medium/medium-api-docs). There is currently some feature enhancements that are listed there related to this report. [management and engaging users](https://github.com/Medium/medium-api-docs/issues/37) and also adding [stats endpoints](https://github.com/Medium/medium-api-docs/issues/22) are both related to items that you are looking for, and are still open in this repository. At the moment, this is not something that we are working on but will take it into consideration in the future.
